### ISSUE TITLE
Would love it, but how to install it?

### ISSUE THREAD

**Issue by NormanTUD** [EntropyOrg/perl-AI-TensorFlow-Libtensorflow#14]
I couldn't find it. May you post some small section with a few commands someone else may need to install all dependencies and run it?

**Comment by zmughal** [comment]
Hello!

You can use the [Docker images which contain all the dependencies](https://metacpan.org/dist/AI-TensorFlow-Libtensorflow/view/lib/AI/TensorFlow/Libtensorflow/Manual/Quickstart.pod#DOCKER-IMAGES). These images are the same as what is used to run the repo on Binder <https://mybinder.org/>.

If you want to install locally, installation via a CPAN client works:
```shell
cpanm AI::TensorFlow::Libtensorflow
```

Please let me know if you run into any problems with installation.

**Comment by davehodg** [comment]
I was about to post the same question.

At the very least mention:

_dzil build
dzil authordeps --missing | cpanm (why both?)
dzil test_

In README.md, and how to use the docker image too.

**Comment by zmughal** [comment]
The Docker image usage is documented in the manual that I linked. `dzil` is only needed for development / authoring straight from the source VCS checkout.
