### ISSUE TITLE
"cpanm --verbose Dist::Zilla::PluginBundle::Author::ZMUGHAL" fails

### ISSUE THREAD

**Issue by davehodg** [EntropyOrg/perl-AI-TensorFlow-Libtensorflow#15]
With:

/00_compile.t .............................. ok   
t/01_scan_file.t ............................ No subtests run 
t/02_scan_string.t .......................... No subtests run 
t/03_scan_tokens.t .......................... No subtests run 
t/04_scan_module.t .......................... No subtests run 
t/10_moose_extends.t ........................ ok   
t/11_version_method.t ....................... ok   
t/12_parameterized_roles.t .................. ok   
t/20_left_paran_is_behind_at_module_name.t .. ok   
t/30_v_string.t ............................. ok   
t/40_extra_scanners.t ....................... ok   

Test Summary Report
-------------------
t/01_scan_file.t                          (Wstat: 11 Tests: 0 Failed: 0)
  Non-zero wait status: 11
  Parse errors: No plan found in TAP output
t/02_scan_string.t                        (Wstat: 11 Tests: 0 Failed: 0)
  Non-zero wait status: 11
  Parse errors: No plan found in TAP output
t/03_scan_tokens.t                        (Wstat: 11 Tests: 0 Failed: 0)
  Non-zero wait status: 11
  Parse errors: No plan found in TAP output
t/04_scan_module.t                        (Wstat: 11 Tests: 0 Failed: 0)
  Non-zero wait status: 11
  Parse errors: No plan found in TAP output
Files=11, Tests=12,  1 wallclock secs ( 0.05 usr  0.03 sys +  0.99 cusr  0.22 csys =  1.29 CPU)
Result: FAIL
FAIL

**Comment by mohawk2** [comment]
Why is this being reported on this repo?

**Comment by zmughal** [comment]
That's due to an upstream develop dependency bug <https://github.com/moznion/Perl-PrereqScanner-Lite/issues/20>. You shouldn't need to install that to use the module. The code for this repo is on CPAN and can be installed directly from CPAN.

**Comment by davehodg** [comment]
cpanm --verbose Perl::PrereqScanner::Lite is exactly the same. 

cpanm  AI::TensorFlow::Libtensorflow works, now the tests pass. But it still doesn't install cleanly.

**Comment by zmughal** [comment]
It would be nice if the `Perl::PrereqScanner::Lite` test got fixed, but that is unrelated to this repository. I'd fix it if I had time, but that's pretty low priority for me at this time.
